### ISSUE TITLE
RMU具体型号

### ISSUE THREAD

**Issue by UAVlover** [ZJU-FAST-Lab/VID-Fusion#1]
hello, 丁博您好，
       非常感谢您开源这个工作。我想请问一下，您这个工作中RMU的具体型号是什么呢？我想有机会实物跑一下您的工作。 @zmdingnav

**Comment by zmdingnav** [comment]
您好，RMU硬件是使用好盈电调专用转速传感器+[自制电路板读取PWM](https://github.com/YangTiankai/Sensorless-brushless-motor-speed-measurement)，然后机载电脑上用FFT计算转速。如果不想添加额外的硬件，推荐使用APM飞控+BDSHOT，可以直接读取转速信息

**Comment by UAVlover** [comment]
> 您好，RMU硬件是使用好盈电调专用转速传感器+[自制电路板读取PWM](https://github.com/YangTiankai/Sensorless-brushless-motor-speed-measurement)，然后机载电脑上用FFT计算转速。如果不想添加额外的硬件，推荐使用APM飞控+BDSHOT，可以直接读取转速信息

好的，感谢丁博的回复
